version: 2
jobs:
  quality:
    docker:
      - image: python:3

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: quality

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m pip install tox
      - run:
          name: check quality
          command: |
            tox

  test_py36: &test-template
    docker:
      - image: python:3.6

    working_directory: ~/repo

    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: py36

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m pip install tox
      - run:
          name: run tests
          command: |
            tox

  test_py37:
    <<: *test-template
    docker:
      - image: python:3.7

    environment:
      TOXENV: py37

  test_py38:
    <<: *test-template
    docker:
      - image: python:3.8

    environment:
      TOXENV: py38

  coverage:
    <<: *test-template

    environment:
      TOXENV: coverage

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python -m pip install tox
      - run:
          name: measure coverage
          command: |
            tox
      - run:
          name: upload report
          command: |
            python -m pip install codecov
            codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
      - test_py36:
          requires:
            - quality
      - test_py37:
          requires:
            - quality
      - test_py38:
          requires:
            - quality
      - coverage:
          requires:
            - quality
